### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device when running the training

### ISSUE THREAD

**Issue by prenc** [dgSPARSE/dgNN#8]
Hi, I am trying to run your framework and I have come across such a problem.

```
Traceback (most recent call last):
  File "/scratch/snx3000/prenc/dgNN/dgNN/script/train/train_gatconv.py", line 202, in <module>
    main(args)
  File "/scratch/snx3000/prenc/dgNN/dgNN/script/train/train_gatconv.py", line 129, in main
    logits = model(features)
  File "/scratch/snx3000/prenc/dgnn-venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/snx3000/prenc/dgNN/dgNN/script/train/train_gatconv.py", line 52, in forward
    logits = self.gat_layers[-1](self.row_ptr,self.col_idx,self.col_ptr,self.row_idx,self.permute,h).mean(1)
  File "/scratch/snx3000/prenc/dgnn-venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/snx3000/prenc/dgNN/dgNN/layers/gatconv_layer.py", line 72, in forward
    h=self.feat_drop(h)
  File "/scratch/snx3000/prenc/dgnn-venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/snx3000/prenc/dgnn-venv/lib/python3.9/site-packages/torch/nn/modules/dropout.py", line 59, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/scratch/snx3000/prenc/dgnn-venv/lib/python3.9/site-packages/torch/nn/functional.py", line 1252, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

The error seems to be related to pytorch however the environment works properly when I run the following commands. Have you encountered something like this?
```
Python 3.9.16 (main, Mar  8 2023, 14:00:05)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import sys
>>> print('A', sys.version)
A 3.9.16 (main, Mar  8 2023, 14:00:05)
[GCC 11.2.0]
>>> print('B', torch.__version__)
B 2.0.0
>>> print('C', torch.cuda.is_available())
C True
>>> print('D', torch.backends.cudnn.enabled)
D True
>>> device = torch.device('cuda')
>>> print('E', torch.cuda.get_device_properties(device))
E _CudaDeviceProperties(name='Tesla P100-PCIE-16GB', major=6, minor=0, total_memory=16280MB, multi_processor_count=56)
>>> print('F', torch.tensor([1.0, 2.0]).cuda())
F tensor([1., 2.], device='cuda:0')
```

**Comment by prenc** [comment]
Worked for thePytorch version 1.13.1+cu117, I have tried multiple other versions before, and the problem appeared. Mb it will help somebody in the future.
